basePath: /v1
info:
  contact: {}
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://github.com/mingjiezxc
  title: Ping Agnet Manager Api
  version: "1.0"
paths:
  /ping:
    get:
      consumes:
      - text/plain
      description: ping
      responses:
        "200":
          description: pong
          schema:
            type: strng
      summary: a ping api
swagger: "2.0"
